// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activity" | "/agents" | "/agents/[address]" | "/agents/register" | "/analytics" | "/bridge" | "/explore" | "/explore/[symbol]" | "/faucet" | "/governance" | "/governance/analytics" | "/invite" | "/lend" | "/perps" | "/perps/leaderboard" | "/perps/portfolio" | "/pool" | "/portfolio" | "/predict" | "/predict/[marketId]" | "/predict/create" | "/predict/portfolio" | "/stable" | "/stocks" | "/stocks/[...invalid]" | "/stocks/[ticker]" | "/stocks/markets" | "/stocks/portfolio" | "/stocks/watchlist" | "/test-dashboard" | "/testnet-guide" | "/tests" | "/ubi-impact" | "/yield"
type AppRouteHandlerRoutes = "/api/[...slug]" | "/api/analytics/overview" | "/api/csp-report" | "/api/faucet" | "/api/feedback" | "/api/hedge/proof/latest" | "/api/hedge/status" | "/api/oracle/status" | "/api/predict/comments" | "/api/prices" | "/api/rpc" | "/api/status" | "/api/status/quotes" | "/api/stocks/rebalance-status"
type PageRoutes = never
type LayoutRoutes = "/" | "/activity" | "/agents" | "/bridge" | "/explore" | "/faucet" | "/governance" | "/lend" | "/perps" | "/pool" | "/portfolio" | "/predict" | "/predict/create" | "/stable" | "/stocks" | "/testnet-guide" | "/ubi-impact" | "/yield"
type RedirectRoutes = "/stocks/markets" | "/swap"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/activity": {}
  "/agents": {}
  "/agents/[address]": { "address": string; }
  "/agents/register": {}
  "/analytics": {}
  "/api/[...slug]": { "slug": string[]; }
  "/api/analytics/overview": {}
  "/api/csp-report": {}
  "/api/faucet": {}
  "/api/feedback": {}
  "/api/hedge/proof/latest": {}
  "/api/hedge/status": {}
  "/api/oracle/status": {}
  "/api/predict/comments": {}
  "/api/prices": {}
  "/api/rpc": {}
  "/api/status": {}
  "/api/status/quotes": {}
  "/api/stocks/rebalance-status": {}
  "/bridge": {}
  "/explore": {}
  "/explore/[symbol]": { "symbol": string; }
  "/faucet": {}
  "/governance": {}
  "/governance/analytics": {}
  "/invite": {}
  "/lend": {}
  "/perps": {}
  "/perps/leaderboard": {}
  "/perps/portfolio": {}
  "/pool": {}
  "/portfolio": {}
  "/predict": {}
  "/predict/[marketId]": { "marketId": string; }
  "/predict/create": {}
  "/predict/portfolio": {}
  "/stable": {}
  "/stocks": {}
  "/stocks/[...invalid]": { "invalid": string[]; }
  "/stocks/[ticker]": { "ticker": string; }
  "/stocks/markets": {}
  "/stocks/portfolio": {}
  "/stocks/watchlist": {}
  "/swap": {}
  "/test-dashboard": {}
  "/testnet-guide": {}
  "/tests": {}
  "/ubi-impact": {}
  "/yield": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/activity": never
  "/agents": never
  "/bridge": never
  "/explore": never
  "/faucet": never
  "/governance": never
  "/lend": never
  "/perps": never
  "/pool": never
  "/portfolio": never
  "/predict": never
  "/predict/create": never
  "/stable": never
  "/stocks": never
  "/testnet-guide": never
  "/ubi-impact": never
  "/yield": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
