// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(app)/agents/[address]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/[address]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/agents/[address]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/agents/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/register">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/agents/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/bridge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bridge">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/bridge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/explore/[symbol]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore/[symbol]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/explore/[symbol]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/faucet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faucet">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/faucet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/governance/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governance/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/governance/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governance">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/lend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lend">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/lend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/perps/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perps/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/perps/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/perps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perps">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/perps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/perps/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perps/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/perps/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/pool/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pool">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/pool/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/[marketId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predict/[marketId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/[marketId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predict/create">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predict">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predict/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stable">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/[...invalid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/[...invalid]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/[...invalid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/[ticker]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/[ticker]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/[ticker]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/markets">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stocks/watchlist">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/test-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/test-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/testnet-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testnet-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/testnet-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/ubi-impact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ubi-impact">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/ubi-impact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/yield/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yield">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/yield/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tests">> = Specific
  const handler = {} as typeof import("../../../src/app/tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analytics/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analytics/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/csp-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/csp-report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/csp-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/faucet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/faucet">> = Specific
  const handler = {} as typeof import("../../../src/app/api/faucet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hedge/proof/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hedge/proof/latest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hedge/proof/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hedge/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hedge/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hedge/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oracle/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oracle/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oracle/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/predict/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/predict/comments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/predict/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rpc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rpc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/status/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status/quotes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/status/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stocks/rebalance-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks/rebalance-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stocks/rebalance-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(app)/agents/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/agents/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/bridge/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/bridge">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/bridge/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/explore/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/explore/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/faucet/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faucet">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/faucet/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/governance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/governance">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/governance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/lend/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lend">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/lend/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/perps/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/perps">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/perps/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/pool/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pool">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/pool/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/portfolio/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/portfolio/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/create/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/predict/create">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/create/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/predict/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/predict">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/predict/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stable/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/stable">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stable/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/stocks/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/stocks">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/stocks/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/testnet-guide/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/testnet-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/testnet-guide/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/ubi-impact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ubi-impact">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/ubi-impact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/yield/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/yield">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/yield/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/activity/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/activity/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
