-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 00_chain_health.sql
-- Title  : Chain health — block & tx volume, 7-day rolling window
-- Kind   : chain_health
-- Routes : (none — chain-health query)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- 7-day chain health: block count, tx count, gas usage, unique active
-- addresses. Uses raw Dune tables that every vendor ships on day 1.

WITH window_blocks AS (
    SELECT *
    FROM   {{blockchain}}.blocks
    WHERE  time >= NOW() - INTERVAL '7' DAY
),
window_txs AS (
    SELECT *
    FROM   {{blockchain}}.transactions
    WHERE  block_time >= NOW() - INTERVAL '7' DAY
)
SELECT
    DATE_TRUNC('day', b.time)                       AS day,
    COUNT(DISTINCT b.number)                        AS block_count,
    SUM(CARDINALITY(b.transactions))                AS tx_count,
    AVG(b.gas_used) / AVG(b.gas_limit)              AS avg_gas_utilisation,
    COUNT(DISTINCT t."from")                        AS unique_senders
FROM   window_blocks b
LEFT JOIN window_txs t
       ON t.block_number = b.number
GROUP BY 1
ORDER BY 1 DESC
