-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 02_ubi_fees_by_protocol.sql
-- Title  : UBI fee events grouped by protocol
-- Kind   : union_all_routes_by_protocol
-- Routes : ALL 14 (ids 1..14)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- UBI fee-emitting events grouped by protocol. One row per protocol.

WITH all_routes AS (
    -- route  1: swap/v4_hook
    SELECT
    1                                AS fee_route_id,
    'swap'                        AS protocol,
    'v4_hook'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xbc242f5093768aa93572c8496fa881527bd1bbb323867dd5f420727783b4eead
      AND contract_address = 0xd7acb2708f0d12efd9f02326c98fc56971dfcd9a
    UNION ALL
    -- route  2: swap/cross_chain_bridge
    SELECT
    2                                AS fee_route_id,
    'swap'                        AS protocol,
    'cross_chain_bridge'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xe01bcae5c6f2b7cec9d50a7134a8ab35ac3cf8d770115e10a2662093abeb4988
      AND contract_address = 0x1291be112d480055dafd8a610b7d1e203891c274
    UNION ALL
    -- route  3: perps/trading_fee
    SELECT
    3                                AS fee_route_id,
    'perps'                        AS protocol,
    'trading_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xe51ed7f1055ec8295a7c4d3aa7e1e9c405571a96ec82a20f8bfec8c5301dae32
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route  4: perps/funding_fee
    SELECT
    4                                AS fee_route_id,
    'perps'                        AS protocol,
    'funding_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x85da25fdd17804a960fc18d208d012780f3a5be91b204774c8a1a95e0f7c04d6
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route  5: perps/liquidation_fee
    SELECT
    5                                AS fee_route_id,
    'perps'                        AS protocol,
    'liquidation_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x08acc47cf71c89e6c22b1d4d5f8ff4534597e3fd3ce984a7c416ffe5cad62d5b
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route  6: predict/market_creation_fee
    SELECT
    6                                AS fee_route_id,
    'predict'                        AS protocol,
    'market_creation_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xf8f449ed6ff79644d8e4e873d43862bed27d3d68aca8a0b36c94de61645df71f
      -- contract_address pending — event source (PredictUBIFeeSplitter) not yet deployed
    UNION ALL
    -- PENDING DEPLOY: source contract OptimisticResolver is not yet in op-stack/addresses.json
    -- route  7: predict/resolver_fee
    SELECT
    7                                AS fee_route_id,
    'predict'                        AS protocol,
    'resolver_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xd915a7fdfe33fe83973299cbc2c22a3b4f9f820e9922ba44a2ef4ebb2eb51390
      -- contract_address pending — event source (OptimisticResolver) not yet deployed
    UNION ALL
    -- route  8: lend/reserve_factor
    SELECT
    8                                AS fee_route_id,
    'lend'                        AS protocol,
    'reserve_factor'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x4a9f0bc4fa7e0e0d70aba96482e6e4dadf15298daff23a34b937566acd51b393
      AND contract_address = 0xcbeaf3bde82155f56486fb5a1072cb8baaf547cc
    UNION ALL
    -- route  9: stable/stability_fee
    SELECT
    9                                AS fee_route_id,
    'stable'                        AS protocol,
    'stability_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x156e588d1067ba3c8a6a7f4376ef70794f8afed114dc9d1421e054b65743e630
      AND contract_address = 0x3489745eff9525ccc3d8c648102fe2cf3485e228
    UNION ALL
    -- route 10: stable/minting_fee
    SELECT
    10                                AS fee_route_id,
    'stable'                        AS protocol,
    'minting_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xc91682597e50d783bf81329b763263cef72b0cda71f5e617e0bd4b4150f84403
      AND contract_address = 0x9eb52339b52e71b1efd5537947e75d23b3a7719b
    UNION ALL
    -- PENDING DEPLOY: source contract StableUBIFeeSplitter is not yet in op-stack/addresses.json
    -- route 11: stable/liquidation_penalty
    SELECT
    11                                AS fee_route_id,
    'stable'                        AS protocol,
    'liquidation_penalty'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x5e8b853c1e291ab51168b5ab87544a6ab0e724af5f0b9b8ecad3b5c3c4e16f1a
      -- contract_address pending — event source (StableUBIFeeSplitter) not yet deployed
    UNION ALL
    -- PENDING DEPLOY: source contract StableUBIFeeSplitter is not yet in op-stack/addresses.json
    -- route 12: stable/governance_fee
    SELECT
    12                                AS fee_route_id,
    'stable'                        AS protocol,
    'governance_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xa6a71206c08a4d3d7b84324b1bdb50b29b4e4aa6637cabafcc3b459161442b74
      -- contract_address pending — event source (StableUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route 13: stocks/trading_fee
    SELECT
    13                                AS fee_route_id,
    'stocks'                        AS protocol,
    'trading_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x5503d47cba7f0b1b3a1343b3831327875fe679575c535fdad0642a7e97973f65
      -- contract_address pending — event source (StocksUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route 14: stocks/liquidation_remnant
    SELECT
    14                                AS fee_route_id,
    'stocks'                        AS protocol,
    'liquidation_remnant'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xf8f449ed6ff79644d8e4e873d43862bed27d3d68aca8a0b36c94de61645df71f
      -- contract_address pending — event source (StocksUBIFeeSplitter) not yet deployed
)
SELECT
    protocol,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT fee_route_id)                    AS routes_seen,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   all_routes
GROUP BY 1
ORDER BY fee_events DESC
