-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 04_swap_volume_by_pool.sql
-- Title  : Swap (V4) — UBIFeeHook events grouped by pool
-- Kind   : single_event_by_indexed
-- Routes : [1]
--          route  1: swap/v4_hook — UBIFeeHook.UBIFeeCollected(address,uint256,uint256,address)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- Swap V4 ``UBIFeeHook.UBIFeeCollected(address pool, uint256 fee, uint256 ubi, address token)``
-- grouped by the indexed `pool` argument (topic1) and the indexed `token`
-- (topic2) when the vendor decodes the event. Until decoded tables are
-- available, this reports raw event counts grouped by topic1 ("pool")
-- which Dune exposes natively on the ``logs`` table.

SELECT
    topic1                                          AS pool_topic,
    topic2                                          AS token_topic,
    COUNT(*)                                        AS hook_events,
    COUNT(DISTINCT tx_hash)                         AS unique_swaps,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   {{blockchain}}.logs
WHERE  topic0 = 0xbc242f5093768aa93572c8496fa881527bd1bbb323867dd5f420727783b4eead
  AND contract_address = 0xd7acb2708f0d12efd9f02326c98fc56971dfcd9a
GROUP BY 1, 2
ORDER BY hook_events DESC
LIMIT  100
