-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 05_perps_trading_fees.sql
-- Title  : Perps — trading + funding + liquidation fee events
-- Kind   : multi_event_by_route
-- Routes : [3, 4, 5]
--          route  3: perps/trading_fee — PerpUBIFeeSplitter.TradingFeeSplit(address,uint256,uint256,uint256)
--          route  4: perps/funding_fee — PerpUBIFeeSplitter.FundingFeeSplit(uint256,uint256,uint256)
--          route  5: perps/liquidation_fee — PerpUBIFeeSplitter.LiquidationUBI(address,address,uint256,uint256)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- Perps — trading + funding + liquidation fee events.
-- Per-route breakdown — one branch per fee route, all UNION ALL'd into a
-- single result. Sub-totals are reported per route id; vendors can roll
-- the columns up further as needed.

WITH route_events AS (
    -- route  3: perps/trading_fee
    SELECT
    3                                AS fee_route_id,
    'perps'                        AS protocol,
    'trading_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xe51ed7f1055ec8295a7c4d3aa7e1e9c405571a96ec82a20f8bfec8c5301dae32
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route  4: perps/funding_fee
    SELECT
    4                                AS fee_route_id,
    'perps'                        AS protocol,
    'funding_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x85da25fdd17804a960fc18d208d012780f3a5be91b204774c8a1a95e0f7c04d6
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route  5: perps/liquidation_fee
    SELECT
    5                                AS fee_route_id,
    'perps'                        AS protocol,
    'liquidation_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x08acc47cf71c89e6c22b1d4d5f8ff4534597e3fd3ce984a7c416ffe5cad62d5b
      -- contract_address pending — event source (PerpUBIFeeSplitter) not yet deployed
)
SELECT
    fee_route_id,
    protocol,
    kind,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   route_events
GROUP BY 1, 2, 3
ORDER BY fee_events DESC
