-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 06_predict_resolution_fees.sql
-- Title  : Predict — market creation + resolver fee events
-- Kind   : multi_event_by_route
-- Routes : [6, 7]
--          route  6: predict/market_creation_fee — PredictUBIFeeSplitter.FeeSplit(address,string,uint256,uint256,uint256,uint256)
--          route  7: predict/resolver_fee — OptimisticResolver.ResolutionFinalized(uint256,bool,bool) (PENDING DEPLOY)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- Predict — market creation + resolver fee events.
-- Per-route breakdown — one branch per fee route, all UNION ALL'd into a
-- single result. Sub-totals are reported per route id; vendors can roll
-- the columns up further as needed.

WITH route_events AS (
    -- route  6: predict/market_creation_fee
    SELECT
    6                                AS fee_route_id,
    'predict'                        AS protocol,
    'market_creation_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xf8f449ed6ff79644d8e4e873d43862bed27d3d68aca8a0b36c94de61645df71f
      -- contract_address pending — event source (PredictUBIFeeSplitter) not yet deployed
    UNION ALL
    -- PENDING DEPLOY: source contract OptimisticResolver is not yet in op-stack/addresses.json
    -- route  7: predict/resolver_fee
    SELECT
    7                                AS fee_route_id,
    'predict'                        AS protocol,
    'resolver_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xd915a7fdfe33fe83973299cbc2c22a3b4f9f820e9922ba44a2ef4ebb2eb51390
      -- contract_address pending — event source (OptimisticResolver) not yet deployed
)
SELECT
    fee_route_id,
    protocol,
    kind,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   route_events
GROUP BY 1, 2, 3
ORDER BY fee_events DESC
