-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 07_lend_treasury_mint.sql
-- Title  : Lend — TreasuryMint reserve-factor events
-- Kind   : single_event_by_topic
-- Routes : [8]
--          route  8: lend/reserve_factor — GoodLendPool.TreasuryMint(address,uint256)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- GoodLendPool.TreasuryMint(address to, uint256 amount).
-- `to` is the UBIFeeSplitter (sink) and `amount` is in gToken (gUSDC etc).
-- For raw bytes-decode (no decoded table yet), `amount` lives at data[1:32].

SELECT
    DATE_TRUNC('day', block_time)                   AS day,
    contract_address                                AS pool_address,
    topic1                                          AS to_topic,     -- indexed `to`
    COUNT(*)                                        AS mint_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    -- bytea2numeric is the Dune V2 helper for raw uint256 decode. If the
    -- chain is on Spellbook V1 use `bytea_to_int256` instead.
    SUM(bytea2numeric(substr(data, 1, 32)))         AS amount_sum_raw
FROM   {{blockchain}}.logs
WHERE  topic0 = 0x4a9f0bc4fa7e0e0d70aba96482e6e4dadf15298daff23a34b937566acd51b393
  AND  contract_address = 0xcbeaf3bde82155f56486fb5a1072cb8baaf547cc
GROUP BY 1, 2, 3
ORDER BY 1 DESC, mint_events DESC
