-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 08_stable_vault_fees.sql
-- Title  : Stable — VaultManager + PegStabilityModule + StableUBIFeeSplitter
-- Kind   : multi_event_by_route
-- Routes : [9, 10, 11, 12]
--          route  9: stable/stability_fee — VaultManager.FeeCollected(bytes32,uint256)
--          route 10: stable/minting_fee — PegStabilityModule.SwapUSDCForGUSD(address,uint256,uint256,uint256)
--          route 11: stable/liquidation_penalty — StableUBIFeeSplitter.LiquidationPenaltySplit(bytes32,address,uint256,uint256) (PENDING DEPLOY)
--          route 12: stable/governance_fee — StableUBIFeeSplitter.GovernanceFeeSplit(address,uint256,uint256) (PENDING DEPLOY)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- Stable — VaultManager + PegStabilityModule + StableUBIFeeSplitter.
-- Per-route breakdown — one branch per fee route, all UNION ALL'd into a
-- single result. Sub-totals are reported per route id; vendors can roll
-- the columns up further as needed.

WITH route_events AS (
    -- route  9: stable/stability_fee
    SELECT
    9                                AS fee_route_id,
    'stable'                        AS protocol,
    'stability_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x156e588d1067ba3c8a6a7f4376ef70794f8afed114dc9d1421e054b65743e630
      AND contract_address = 0x3489745eff9525ccc3d8c648102fe2cf3485e228
    UNION ALL
    -- route 10: stable/minting_fee
    SELECT
    10                                AS fee_route_id,
    'stable'                        AS protocol,
    'minting_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xc91682597e50d783bf81329b763263cef72b0cda71f5e617e0bd4b4150f84403
      AND contract_address = 0x9eb52339b52e71b1efd5537947e75d23b3a7719b
    UNION ALL
    -- PENDING DEPLOY: source contract StableUBIFeeSplitter is not yet in op-stack/addresses.json
    -- route 11: stable/liquidation_penalty
    SELECT
    11                                AS fee_route_id,
    'stable'                        AS protocol,
    'liquidation_penalty'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x5e8b853c1e291ab51168b5ab87544a6ab0e724af5f0b9b8ecad3b5c3c4e16f1a
      -- contract_address pending — event source (StableUBIFeeSplitter) not yet deployed
    UNION ALL
    -- PENDING DEPLOY: source contract StableUBIFeeSplitter is not yet in op-stack/addresses.json
    -- route 12: stable/governance_fee
    SELECT
    12                                AS fee_route_id,
    'stable'                        AS protocol,
    'governance_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xa6a71206c08a4d3d7b84324b1bdb50b29b4e4aa6637cabafcc3b459161442b74
      -- contract_address pending — event source (StableUBIFeeSplitter) not yet deployed
)
SELECT
    fee_route_id,
    protocol,
    kind,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   route_events
GROUP BY 1, 2, 3
ORDER BY fee_events DESC
