-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py
-- Source of truth: analytics/address-book.json
-- Regenerate: python scripts/build-dune-package.py --output analytics/dune-package

--
-- Query  : 09_stocks_trading_fees.sql
-- Title  : Stocks — synthetic-stock trading + liquidation fee events
-- Kind   : multi_event_by_route
-- Routes : [13, 14]
--          route 13: stocks/trading_fee — StocksUBIFeeSplitter.TradingFeeSplit(address,string,uint256,uint256)
--          route 14: stocks/liquidation_remnant — StocksUBIFeeSplitter.FeeSplit(address,string,uint256,uint256,uint256,uint256)
--
-- Placeholders:
--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is
--                     indexed (e.g. `gooddollar_l2`). Replace at use.
--
-- Stocks — synthetic-stock trading + liquidation fee events.
-- Per-route breakdown — one branch per fee route, all UNION ALL'd into a
-- single result. Sub-totals are reported per route id; vendors can roll
-- the columns up further as needed.

WITH route_events AS (
    -- route 13: stocks/trading_fee
    SELECT
    13                                AS fee_route_id,
    'stocks'                        AS protocol,
    'trading_fee'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0x5503d47cba7f0b1b3a1343b3831327875fe679575c535fdad0642a7e97973f65
      -- contract_address pending — event source (StocksUBIFeeSplitter) not yet deployed
    UNION ALL
    -- route 14: stocks/liquidation_remnant
    SELECT
    14                                AS fee_route_id,
    'stocks'                        AS protocol,
    'liquidation_remnant'                            AS kind,
    block_time,
    block_number,
    tx_hash,
    contract_address                          AS event_contract_address
    FROM   {{blockchain}}.logs
    WHERE  topic0 = 0xf8f449ed6ff79644d8e4e873d43862bed27d3d68aca8a0b36c94de61645df71f
      -- contract_address pending — event source (StocksUBIFeeSplitter) not yet deployed
)
SELECT
    fee_route_id,
    protocol,
    kind,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   route_events
GROUP BY 1, 2, 3
ORDER BY fee_events DESC
