#!/usr/bin/env python3
"""Build the Dune / indexing-request package from the analytics address book.

Iteration 28 of ``docs/TESTNET-READINESS-50-ITERATIONS.md`` requires a
self-contained directory that any third-party indexing vendor
(Dune Analytics, Allium, Goldsky, Subsquid, ...) can use to onboard
GoodDollar L2 even though chain indexing has not yet been provisioned.

The package consists of:

* ``INDEXING_MANIFEST.json`` — machine-readable chain + contract +
  event + fee-route inventory, derived 1:1 from
  ``analytics/address-book.json``.
* ``queries/*.sql`` — 12 canonical Dune-style SQL files filtering by
  ``topic0`` / ``contract_address`` placeholders pre-resolved from
  the address book.
* ``README.md`` — onboarding brief + fee-routes table.
* ``.generated-from`` — SHA-256 of the address book consumed, so any
  drift between the package and its input is one ``shasum`` away.

The generator is **offline and deterministic**:

* It reads only ``analytics/address-book.json``.
* It writes files only under ``analytics/dune-package/``.
* No RPC, no ``forge build``, no network.

Usage::

    python scripts/build-dune-package.py --output analytics/dune-package
    python scripts/build-dune-package.py --output analytics/dune-package --check
    python scripts/build-dune-package.py --output analytics/dune-package --no-timestamp

In ``--check`` mode the generator regenerates in memory, normalises the
``generated_at`` field, diffs against the committed files, and exits
non-zero on any mismatch. This is the regression guard the pytest
companion (``scripts/test_build_dune_package.py``) uses to assert that
nobody hand-edits the SQL files out of sync with the address book.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import difflib
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
ADDRESS_BOOK_PATH = REPO_ROOT / "analytics" / "address-book.json"

ARTIFACT_VERSION = "1"
TIMESTAMP_SENTINEL = "1970-01-01T00:00:00Z"

# ---------------------------------------------------------------------------
# Static metadata for the chain / vendor links. These are baked into the
# generator because they are public-product decisions, not contract data.
# If they change, bump the constants here and regenerate.
# ---------------------------------------------------------------------------

CHAIN_DEFAULT_NAME = "GoodDollar L2 Devnet"
CHAIN_FAUCET_URL = "https://goodswap.goodclaw.org/faucet"
CHAIN_BRIDGE_URL = "https://goodswap.goodclaw.org/portfolio"
CHAIN_DOCS_URL = "https://goodswap.goodclaw.org/testnet-guide"
CHAIN_DAPP_URL = "https://goodswap.goodclaw.org"
CHAIN_REPO_URL = "https://github.com/GoodDollar/gooddollar-l2"
CHAIN_CONTACT = "ops@gooddollar.org"

DO_NOT_EDIT_BANNER = (
    "-- DO NOT EDIT BY HAND — generated by scripts/build-dune-package.py\n"
    "-- Source of truth: analytics/address-book.json\n"
    "-- Regenerate: python scripts/build-dune-package.py "
    "--output analytics/dune-package\n"
)

# ---------------------------------------------------------------------------
# Query catalogue. Each entry maps to one .sql file. Routes referenced by
# id are validated by the pytest against analytics/address-book.json.
# ---------------------------------------------------------------------------

QueryDef = dict[str, Any]

QUERY_CATALOGUE: list[QueryDef] = [
    {
        "filename": "00_chain_health.sql",
        "title": "Chain health — block & tx volume, 7-day rolling window",
        "fee_route_ids": [],  # chain-health query, intentionally no route
        "kind": "chain_health",
    },
    {
        "filename": "01_ubi_fees_total.sql",
        "title": "Total UBI fee events — union of all 14 routes",
        "fee_route_ids": "ALL",
        "kind": "union_all_routes",
    },
    {
        "filename": "02_ubi_fees_by_protocol.sql",
        "title": "UBI fee events grouped by protocol",
        "fee_route_ids": "ALL",
        "kind": "union_all_routes_by_protocol",
    },
    {
        "filename": "03_ubi_fees_daily.sql",
        "title": "Daily UBI fee event curve — 90-day rolling window",
        "fee_route_ids": "ALL",
        "kind": "union_all_routes_daily",
    },
    {
        "filename": "04_swap_volume_by_pool.sql",
        "title": "Swap (V4) — UBIFeeHook events grouped by pool",
        "fee_route_ids": [1],
        "kind": "single_event_by_indexed",
    },
    {
        "filename": "05_perps_trading_fees.sql",
        "title": "Perps — trading + funding + liquidation fee events",
        "fee_route_ids": [3, 4, 5],
        "kind": "multi_event_by_route",
    },
    {
        "filename": "06_predict_resolution_fees.sql",
        "title": "Predict — market creation + resolver fee events",
        "fee_route_ids": [6, 7],
        "kind": "multi_event_by_route",
    },
    {
        "filename": "07_lend_treasury_mint.sql",
        "title": "Lend — TreasuryMint reserve-factor events",
        "fee_route_ids": [8],
        "kind": "single_event_by_topic",
    },
    {
        "filename": "08_stable_vault_fees.sql",
        "title": "Stable — VaultManager + PegStabilityModule + StableUBIFeeSplitter",
        "fee_route_ids": [9, 10, 11, 12],
        "kind": "multi_event_by_route",
    },
    {
        "filename": "09_stocks_trading_fees.sql",
        "title": "Stocks — synthetic-stock trading + liquidation fee events",
        "fee_route_ids": [13, 14],
        "kind": "multi_event_by_route",
    },
    {
        "filename": "10_top_ubi_payers.sql",
        "title": "Top 100 wallets by count of UBI-emitting transactions",
        "fee_route_ids": "ALL",
        "kind": "top_payers",
    },
    {
        "filename": "11_protocol_activity_30d.sql",
        "title": "UBI-emitting event count per protocol, rolling 30 days",
        "fee_route_ids": "ALL",
        "kind": "protocol_activity_30d",
    },
]


# ---------------------------------------------------------------------------
# Loading + helpers
# ---------------------------------------------------------------------------


def _load_address_book(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(
            f"ERROR: {path} not found. Run "
            f"`python scripts/build-analytics-address-book.py "
            f"--output {path.relative_to(REPO_ROOT)}` first."
        )
    return json.loads(path.read_text())


def _route_by_id(routes: list[dict[str, Any]], rid: int) -> dict[str, Any]:
    for r in routes:
        if r["id"] == rid:
            return r
    raise SystemExit(f"ERROR: fee_route id {rid} not found in address-book.json")


def _all_route_ids(routes: list[dict[str, Any]]) -> list[int]:
    return [r["id"] for r in routes]


def _normalise_addr(addr: str | None) -> str | None:
    """Dune typically lowercases addresses in its raw tables; we follow suit
    in SQL while keeping the original mixed-case in JSON / README."""
    if addr is None:
        return None
    return addr.lower()


def _resolve_addrs_for_route(route: dict[str, Any]) -> tuple[str | None, str | None]:
    """Return (event_contract_address_lower, address_predicate_sql_or_none)."""
    ec_addr = _normalise_addr(route.get("event_contract_address"))
    if ec_addr:
        return ec_addr, f"AND contract_address = {ec_addr}"
    return None, "-- (event_contract_address pending — filter by topic0 only)"


# ---------------------------------------------------------------------------
# SQL builders. Each helper returns the body of a query as a string.
# A common file header (banner + metadata block) is prepended by the
# top-level emitter to keep the per-helper code focused on the query body.
# ---------------------------------------------------------------------------


def _sql_header(query: QueryDef, routes: list[dict[str, Any]]) -> str:
    lines: list[str] = [DO_NOT_EDIT_BANNER, "--"]
    lines.append(f"-- Query  : {query['filename']}")
    lines.append(f"-- Title  : {query['title']}")
    lines.append(f"-- Kind   : {query['kind']}")
    fr = query["fee_route_ids"]
    if fr == "ALL":
        lines.append(f"-- Routes : ALL 14 (ids {_all_route_ids(routes)[0]}..{_all_route_ids(routes)[-1]})")
    elif fr:
        lines.append(f"-- Routes : {fr}")
        for rid in fr:
            r = _route_by_id(routes, rid)
            pending = " (PENDING DEPLOY)" if r["source_address_pending_deploy"] else ""
            lines.append(
                f"--          route {rid:>2}: {r['protocol']}/{r['kind']} "
                f"— {r['event_contract']}.{r['event_signature']}{pending}"
            )
    else:
        lines.append("-- Routes : (none — chain-health query)")
    lines.append("--")
    lines.append("-- Placeholders:")
    lines.append("--   {{blockchain}}  — Dune raw-tables prefix once GoodDollar L2 is")
    lines.append("--                     indexed (e.g. `gooddollar_l2`). Replace at use.")
    lines.append("--")
    return "\n".join(lines) + "\n"


def _sql_chain_health() -> str:
    return """
-- 7-day chain health: block count, tx count, gas usage, unique active
-- addresses. Uses raw Dune tables that every vendor ships on day 1.

WITH window_blocks AS (
    SELECT *
    FROM   {{blockchain}}.blocks
    WHERE  time >= NOW() - INTERVAL '7' DAY
),
window_txs AS (
    SELECT *
    FROM   {{blockchain}}.transactions
    WHERE  block_time >= NOW() - INTERVAL '7' DAY
)
SELECT
    DATE_TRUNC('day', b.time)                       AS day,
    COUNT(DISTINCT b.number)                        AS block_count,
    SUM(CARDINALITY(b.transactions))                AS tx_count,
    AVG(b.gas_used) / AVG(b.gas_limit)              AS avg_gas_utilisation,
    COUNT(DISTINCT t."from")                        AS unique_senders
FROM   window_blocks b
LEFT JOIN window_txs t
       ON t.block_number = b.number
GROUP BY 1
ORDER BY 1 DESC
""".lstrip()


def _route_filter_clause(route: dict[str, Any]) -> str:
    """Per-route filter line used inside UNION ALL bodies."""
    topic = route["event_topic0"]
    ec_addr = _normalise_addr(route.get("event_contract_address"))
    parts = [f"topic0 = {topic}"]
    if ec_addr:
        parts.append(f"contract_address = {ec_addr}")
    else:
        parts.append(
            "-- contract_address pending deploy ("
            f"{route['event_contract']}) — filter by topic0 only"
        )
    return " AND ".join(parts)


def _union_all_block(routes: list[dict[str, Any]], select_extra: str = "") -> str:
    """Return the UNION ALL body, one branch per fee route, with PENDING DEPLOY
    markers on routes whose source is not yet deployed."""
    branches: list[str] = []
    for r in routes:
        pending = r["source_address_pending_deploy"]
        marker = (
            f"    -- PENDING DEPLOY: source contract {r['event_contract']} "
            f"is not yet in op-stack/addresses.json\n"
            if pending
            else ""
        )
        select = (
            "SELECT\n"
            f"    {r['id']}                                AS fee_route_id,\n"
            f"    '{r['protocol']}'                        AS protocol,\n"
            f"    '{r['kind']}'                            AS kind,\n"
            f"    block_time,\n"
            f"    block_number,\n"
            f"    tx_hash,\n"
            f"    contract_address                          AS event_contract_address"
        )
        if select_extra:
            select += "," + select_extra
        topic = r["event_topic0"]
        ec_addr = _normalise_addr(r.get("event_contract_address"))
        if ec_addr:
            filt = f"topic0 = {topic}\n      AND contract_address = {ec_addr}"
        else:
            filt = (
                f"topic0 = {topic}\n      -- contract_address pending — "
                f"event source ({r['event_contract']}) not yet deployed"
            )
        branch = (
            marker
            + f"    -- route {r['id']:>2}: {r['protocol']}/{r['kind']}\n"
            + "    "
            + select
            + "\n    FROM   {{blockchain}}.logs\n"
            + f"    WHERE  {filt}"
        )
        branches.append(branch)
    return "\n    UNION ALL\n".join(branches)


def _sql_ubi_fees_total(routes: list[dict[str, Any]]) -> str:
    body = _union_all_block(routes)
    return f"""
-- Total UBI fee-emitting events across all 14 routes (raw event count).
-- Decoded amount columns (ubi_share, protocol_share) require Dune's
-- ``decoded_logs`` table which becomes available once the vendor enables
-- decoding for each contract. Until then, this query reports event counts
-- per route as a proxy for activity.

WITH all_routes AS (
{body}
)
SELECT
    COUNT(*)                                        AS total_fee_events,
    COUNT(DISTINCT fee_route_id)                    AS active_routes,
    COUNT(DISTINCT protocol)                        AS active_protocols,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   all_routes
""".lstrip()


def _sql_ubi_fees_by_protocol(routes: list[dict[str, Any]]) -> str:
    body = _union_all_block(routes)
    return f"""
-- UBI fee-emitting events grouped by protocol. One row per protocol.

WITH all_routes AS (
{body}
)
SELECT
    protocol,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT fee_route_id)                    AS routes_seen,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   all_routes
GROUP BY 1
ORDER BY fee_events DESC
""".lstrip()


def _sql_ubi_fees_daily(routes: list[dict[str, Any]]) -> str:
    body = _union_all_block(routes)
    return f"""
-- Daily UBI fee-emitting event curve, rolling 90-day window.

WITH all_routes AS (
{body}
)
SELECT
    DATE_TRUNC('day', block_time)                   AS day,
    protocol,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs
FROM   all_routes
WHERE  block_time >= NOW() - INTERVAL '90' DAY
GROUP BY 1, 2
ORDER BY 1 DESC, 2
""".lstrip()


def _sql_swap_volume_by_pool(routes: list[dict[str, Any]]) -> str:
    route = _route_by_id(routes, 1)
    topic = route["event_topic0"]
    ec_addr = _normalise_addr(route.get("event_contract_address")) or (
        "-- address pending deploy"
    )
    filt = f"topic0 = {topic}"
    if route.get("event_contract_address"):
        filt += f"\n  AND contract_address = {ec_addr}"
    return f"""
-- Swap V4 ``UBIFeeHook.UBIFeeCollected(address pool, uint256 fee, uint256 ubi, address token)``
-- grouped by the indexed `pool` argument (topic1) and the indexed `token`
-- (topic2) when the vendor decodes the event. Until decoded tables are
-- available, this reports raw event counts grouped by topic1 ("pool")
-- which Dune exposes natively on the ``logs`` table.

SELECT
    topic1                                          AS pool_topic,
    topic2                                          AS token_topic,
    COUNT(*)                                        AS hook_events,
    COUNT(DISTINCT tx_hash)                         AS unique_swaps,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   {{{{blockchain}}}}.logs
WHERE  {filt}
GROUP BY 1, 2
ORDER BY hook_events DESC
LIMIT  100
""".lstrip()


def _sql_multi_event_by_route(query: QueryDef, routes: list[dict[str, Any]]) -> str:
    subset = [_route_by_id(routes, rid) for rid in query["fee_route_ids"]]
    body = _union_all_block(subset)
    return f"""
-- {query['title']}.
-- Per-route breakdown — one branch per fee route, all UNION ALL'd into a
-- single result. Sub-totals are reported per route id; vendors can roll
-- the columns up further as needed.

WITH route_events AS (
{body}
)
SELECT
    fee_route_id,
    protocol,
    kind,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    MIN(block_time)                                 AS first_event,
    MAX(block_time)                                 AS last_event
FROM   route_events
GROUP BY 1, 2, 3
ORDER BY fee_events DESC
""".lstrip()


def _sql_lend_treasury_mint(routes: list[dict[str, Any]]) -> str:
    route = _route_by_id(routes, 8)
    return f"""
-- GoodLendPool.TreasuryMint(address to, uint256 amount).
-- `to` is the UBIFeeSplitter (sink) and `amount` is in gToken (gUSDC etc).
-- For raw bytes-decode (no decoded table yet), `amount` lives at data[1:32].

SELECT
    DATE_TRUNC('day', block_time)                   AS day,
    contract_address                                AS pool_address,
    topic1                                          AS to_topic,     -- indexed `to`
    COUNT(*)                                        AS mint_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs,
    -- bytea2numeric is the Dune V2 helper for raw uint256 decode. If the
    -- chain is on Spellbook V1 use `bytea_to_int256` instead.
    SUM(bytea2numeric(substr(data, 1, 32)))         AS amount_sum_raw
FROM   {{{{blockchain}}}}.logs
WHERE  topic0 = {route['event_topic0']}
  AND  contract_address = {_normalise_addr(route['event_contract_address'])}
GROUP BY 1, 2, 3
ORDER BY 1 DESC, mint_events DESC
""".lstrip()


def _sql_top_ubi_payers(routes: list[dict[str, Any]]) -> str:
    body = _union_all_block(routes)
    return f"""
-- Top 100 wallets ranked by the number of transactions that emitted at
-- least one UBI-fee event. "Payer" here is the EOA / contract that
-- originated the transaction (`tx.from`), not the contract that emitted
-- the log. Join to ``transactions`` to recover ``from``.

WITH all_routes AS (
{body}
)
SELECT
    t."from"                                        AS payer,
    COUNT(DISTINCT all_routes.tx_hash)              AS fee_txs,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT all_routes.protocol)             AS protocols_touched,
    MIN(all_routes.block_time)                      AS first_event,
    MAX(all_routes.block_time)                      AS last_event
FROM   all_routes
JOIN   {{{{blockchain}}}}.transactions t
       ON t.hash         = all_routes.tx_hash
      AND t.block_number = all_routes.block_number
GROUP BY 1
ORDER BY fee_txs DESC
LIMIT  100
""".lstrip()


def _sql_protocol_activity_30d(routes: list[dict[str, Any]]) -> str:
    body = _union_all_block(routes)
    return f"""
-- Per-protocol rolling-30-day count of UBI-emitting events. One row per
-- (protocol, day) pair so charts can stack protocol contributions.

WITH all_routes AS (
{body}
)
SELECT
    DATE_TRUNC('day', block_time)                   AS day,
    protocol,
    COUNT(*)                                        AS fee_events,
    COUNT(DISTINCT tx_hash)                         AS unique_txs
FROM   all_routes
WHERE  block_time >= NOW() - INTERVAL '30' DAY
GROUP BY 1, 2
ORDER BY 1 DESC, fee_events DESC
""".lstrip()


def _build_query(query: QueryDef, routes: list[dict[str, Any]]) -> str:
    header = _sql_header(query, routes)
    kind = query["kind"]
    if kind == "chain_health":
        body = _sql_chain_health()
    elif kind == "union_all_routes":
        body = _sql_ubi_fees_total(routes)
    elif kind == "union_all_routes_by_protocol":
        body = _sql_ubi_fees_by_protocol(routes)
    elif kind == "union_all_routes_daily":
        body = _sql_ubi_fees_daily(routes)
    elif kind == "single_event_by_indexed":
        body = _sql_swap_volume_by_pool(routes)
    elif kind == "multi_event_by_route":
        body = _sql_multi_event_by_route(query, routes)
    elif kind == "single_event_by_topic":
        # Only used by 07_lend_treasury_mint.sql in the current catalogue.
        body = _sql_lend_treasury_mint(routes)
    elif kind == "top_payers":
        body = _sql_top_ubi_payers(routes)
    elif kind == "protocol_activity_30d":
        body = _sql_protocol_activity_30d(routes)
    else:  # pragma: no cover
        raise SystemExit(f"unknown query kind: {kind!r}")
    return header + body if body.endswith("\n") else header + body + "\n"


# ---------------------------------------------------------------------------
# INDEXING_MANIFEST.json projection
# ---------------------------------------------------------------------------


def _projected_contracts(book: dict[str, Any]) -> list[dict[str, Any]]:
    """Project every deployed (and pending-deploy) contract that carries a
    fee-route event or sink into a flat list keyed by name. Each entry
    references its protocol classification (from the address book's
    ``protocols`` block) and the relevant ABI event topics from
    ``abis.<Name>.events`` so vendors do not need a second lookup."""
    name_to_proto: dict[str, str] = {}
    name_to_addr: dict[str, str | None] = {}
    for proto_key, proto in book["protocols"].items():
        for c in proto["contracts"]:
            name_to_proto[c["name"]] = proto_key
            name_to_addr[c["name"]] = c["address"]

    # Pending-deploy sources/sinks/event-contracts are not in the protocols
    # block (no address). We surface them as pending entries so vendors
    # can pre-stage decoders.
    pending_classification: dict[str, str] = {
        "OptimisticResolver": "predict",
        "PerpUBIFeeSplitter": "perps",
        "PredictUBIFeeSplitter": "predict",
        "StableUBIFeeSplitter": "stable",
        "StocksUBIFeeSplitter": "stocks",
    }

    seen: set[str] = set()
    contracts: list[dict[str, Any]] = []
    for r in book["fee_routes"]:
        for name in (r["event_contract"], r["source_contract"], r["sink_contract"]):
            if name in seen:
                continue
            seen.add(name)
            proto = name_to_proto.get(name) or pending_classification.get(name, "ubi_core")
            addr = name_to_addr.get(name)
            entry: dict[str, Any] = {
                "name": name,
                "address": addr,
                "protocol": proto,
                "pending_deploy": addr is None,
                "events": [],
            }
            abi_doc = book.get("abis", {}).get(name)
            if abi_doc:
                for ev in abi_doc["events"]:
                    entry["events"].append(
                        {
                            "name": ev["name"],
                            "signature": ev["signature"],
                            "topic0": ev["topic0"],
                            "anonymous": ev.get("anonymous", False),
                            "indexed_inputs": [
                                i["name"]
                                for i in ev.get("inputs", [])
                                if i.get("indexed", False)
                            ],
                        }
                    )
                # deterministic ordering inside each contract
                entry["events"].sort(key=lambda e: e["name"])
            contracts.append(entry)

    contracts.sort(key=lambda c: c["name"])
    return contracts


def _projected_fee_routes(book: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for r in book["fee_routes"]:
        out.append(
            {
                "id": r["id"],
                "protocol": r["protocol"],
                "kind": r["kind"],
                "label": r["label"],
                "event_contract": r["event_contract"],
                "event_contract_address": r.get("event_contract_address"),
                "event_signature": r["event_signature"],
                "event_topic0": r["event_topic0"],
                "fee_token": r["fee_token"],
                "sink_contract": r["sink_contract"],
                "sink_address": r.get("sink_address"),
                "sink_address_fallback": r.get("sink_address_fallback"),
                "sink_method": r["sink_method"],
                "pending_deploy": r["source_address_pending_deploy"],
            }
        )
    return out


def _build_manifest(book: dict[str, Any], no_timestamp: bool) -> dict[str, Any]:
    chain = book["chain"]
    generated_at = (
        TIMESTAMP_SENTINEL
        if no_timestamp
        else _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    )
    return {
        "version": ARTIFACT_VERSION,
        "generated_at": generated_at,
        "generator": "scripts/build-dune-package.py",
        "source": "analytics/address-book.json",
        "chain": {
            "id": chain["id"],
            "name": chain.get("name", CHAIN_DEFAULT_NAME),
            "rpc_url": chain["rpc_url"],
            "explorer_url": chain["explorer_url"],
            "faucet_url": CHAIN_FAUCET_URL,
            "bridge_url": CHAIN_BRIDGE_URL,
            "docs_url": CHAIN_DOCS_URL,
            "dapp_url": CHAIN_DAPP_URL,
            "fee_split_bps": book["notes"]["fee_split_bps"],
            "ubi_breakdown_bps": book["notes"]["ubi_breakdown_doc"],
        },
        "contracts": _projected_contracts(book),
        "fee_routes": _projected_fee_routes(book),
        "queries": [
            {
                "filename": q["filename"],
                "title": q["title"],
                "kind": q["kind"],
                "fee_route_ids": (
                    _all_route_ids(book["fee_routes"])
                    if q["fee_route_ids"] == "ALL"
                    else q["fee_route_ids"]
                ),
            }
            for q in QUERY_CATALOGUE
        ],
        "notes": {
            "missing_abis": book["notes"]["missing_abis"],
            "specialised_splitters_pending": book["notes"][
                "specialised_splitters_pending"
            ],
            "ubi_split_doc": book["notes"]["ubi_split_doc"],
            "raw_table_convention": (
                "Queries use {{blockchain}}.logs / .transactions / .blocks. "
                "Replace {{blockchain}} with the indexer's chain prefix once "
                "GoodDollar L2 is onboarded."
            ),
            "decoded_table_convention": (
                "Amount fields are commented out as bytea2numeric(substr(data, ...)) "
                "for the raw-bytes pattern. Once the indexer publishes decoded "
                "tables, replace with the named decoded column."
            ),
        },
    }


# ---------------------------------------------------------------------------
# README projection
# ---------------------------------------------------------------------------


def _render_readme(book: dict[str, Any], manifest: dict[str, Any]) -> str:
    chain = manifest["chain"]
    routes = book["fee_routes"]
    pending = [r for r in routes if r["source_address_pending_deploy"]]

    rows: list[str] = []
    for r in routes:
        pending_mark = " ⏳" if r["source_address_pending_deploy"] else ""
        addr = r.get("event_contract_address") or "_(pending deploy)_"
        rows.append(
            f"| {r['id']:>2} | {r['protocol']} | {r['kind']} | "
            f"`{r['event_contract']}`{pending_mark} | `{addr}` | "
            f"`{r['event_topic0']}` |"
        )
    routes_table = "\n".join(rows)

    pending_lines: list[str] = []
    if pending:
        for r in pending:
            pending_lines.append(
                f"- Route **{r['id']}** ({r['protocol']}/{r['kind']}) — "
                f"event contract `{r['event_contract']}` not yet deployed. "
                f"Topic0 is canonical (`{r['event_topic0']}`); enable "
                f"`contract_address` filter once deployed."
            )
    pending_block = "\n".join(pending_lines) or "_(none — all event contracts deployed)_"

    queries_rows: list[str] = []
    for q in manifest["queries"]:
        route_ids = q["fee_route_ids"]
        if not route_ids:
            cov = "_(chain-wide)_"
        elif len(route_ids) == len(routes):
            cov = f"all {len(route_ids)} routes"
        else:
            cov = ", ".join(str(i) for i in route_ids)
        queries_rows.append(f"| `{q['filename']}` | {q['title']} | {cov} |")
    queries_table = "\n".join(queries_rows)

    splitters_pending = manifest["notes"]["specialised_splitters_pending"]
    splitters_block = (
        "\n".join(f"- `{s}`" for s in splitters_pending)
        if splitters_pending
        else "_(none)_"
    )

    return f"""# GoodDollar L2 — Dune / Indexing Request Package

> **Iter 28 of `docs/TESTNET-READINESS-50-ITERATIONS.md`** — the artifact a
> third-party indexer (Dune Analytics, Allium, Goldsky, Subsquid, etc.)
> needs to onboard GoodDollar L2 even though chain indexing is still
> being provisioned.

This directory is **machine-generated** from
[`analytics/address-book.json`](../address-book.json) — do not hand-edit.
Regenerate any time the address book changes:

```bash
python scripts/build-dune-package.py --output analytics/dune-package
```

A pytest companion at `scripts/test_build_dune_package.py` guards drift.

## 1. Chain quickstart

```jsonc
{{
  "chain_id":      {chain["id"]},
  "name":          "{chain["name"]}",
  "rpc_url":       "{chain["rpc_url"]}",
  "explorer_url":  "{chain["explorer_url"]}",
  "faucet_url":    "{chain["faucet_url"]}",
  "bridge_url":    "{chain["bridge_url"]}",
  "docs_url":      "{chain["docs_url"]}",
  "dapp_url":      "{chain["dapp_url"]}",
  "fee_split_bps": {{ "ubi": {chain["fee_split_bps"]["ubi"]}, "protocol": {chain["fee_split_bps"]["protocol"]} }}
}}
```

## 2. Decode this chain

The package's [`INDEXING_MANIFEST.json`](./INDEXING_MANIFEST.json) lists
every contract that emits a UBI fee event, with the **full ABI event
projection** (signature, `topic0`, indexed input names) and the
protocol it belongs to. Generic-indexer import recipes:

- **Dune V2 (Spellbook)** — submit the manifest as the contract+ABI bundle
  for `gooddollar_l2`. Each `contracts[].events[]` row becomes a
  `decoded_evt_*` view; `topic0` doubles as the lookup key in raw
  `gooddollar_l2.logs`.
- **Allium** — paste each `(address, abi)` pair into
  `event_logs_decoded.<protocol>_<event>` setup; the manifest is already
  normalised to that shape.
- **Goldsky / Subsquid** — feed `contracts[]` into an `evmLog` mapping;
  every `pending_deploy: true` contract is intentionally left without an
  address so the mapping is staged but inactive.

## 3. UBI fee accounting

Every protocol on GoodDollar L2 routes a fixed slice of its fees to a
UBI pool. The canonical specification is
[`docs/UBI-FEE-ACCOUNTING.md`](../../docs/UBI-FEE-ACCOUNTING.md);
this package operationalises §4 (the 14 fee routes table) for
indexing vendors.

Default split: **{chain["fee_split_bps"]["ubi"] / 100:.0f}% UBI / {chain["fee_split_bps"]["protocol"] / 100:.0f}% protocol**.
Inside the UBI slice the on-chain breakdown is:

- `human_ubi_pool_bps`   : {chain["ubi_breakdown_bps"]["human_ubi_pool_bps"]}
- `g_dollar_treasury_bps`: {chain["ubi_breakdown_bps"]["g_dollar_treasury_bps"]}
- `validator_rewards_bps`: {chain["ubi_breakdown_bps"]["validator_rewards_bps"]}

### 3.1 All 14 fee routes

| #  | Protocol | Kind | Event Contract | Address | topic0 |
| -- | -------- | ---- | -------------- | ------- | ------ |
{routes_table}

A ⏳ marker means the route's source contract is in
`docs/UBI-FEE-ACCOUNTING.md` §4 but not yet in
`op-stack/addresses.json` — i.e. **pending deploy**. SQL queries for
these routes are still emitted (with a `PENDING DEPLOY` banner) so
that vendors can enable them with one address edit once the splitter
ships.

### 3.2 Specialised splitters pending deploy

{splitters_block}

### 3.3 Routes pending deploy (event-contract level)

{pending_block}

## 4. Query pack

Twelve canonical Dune-style queries live under
[`queries/`](./queries/). They use `{{{{blockchain}}}}.logs`,
`{{{{blockchain}}}}.transactions`, and `{{{{blockchain}}}}.blocks`
(replace `{{{{blockchain}}}}` with the indexer's chain prefix). Each
file's header lists the fee-route ids it covers and the `topic0` it
filters on, and includes a "DO NOT EDIT BY HAND" banner.

| File | Title | Routes covered |
| ---- | ----- | -------------- |
{queries_table}

Raw-table queries always work. Decoded-amount columns are commented
out as `bytea2numeric(substr(data, ...))` until the vendor publishes
decoded tables.

## 5. Regeneration

```bash
# Rebuild from analytics/address-book.json
python scripts/build-dune-package.py --output analytics/dune-package

# Drift check (used by iter 30's gate)
python scripts/build-dune-package.py --output analytics/dune-package --check

# Stable-timestamp build (for tests / diffs)
python scripts/build-dune-package.py --output analytics/dune-package --no-timestamp
```

`.generated-from` records the SHA-256 of the address book this package
was derived from. If the file disagrees with
`shasum -a 256 analytics/address-book.json`, the package is stale.

## 6. Tests

```bash
pytest scripts/test_build_dune_package.py -v
```

Covers: manifest invariants, `topic0` ↔ address-book parity, SQL header
metadata, PENDING DEPLOY markers, `.generated-from` hash, deterministic
round-trip, and `--check` mode against the committed artefacts.

## 7. Asking us to index your indexer

- **Repo**     : <{CHAIN_REPO_URL}>
- **Contact**  : <{CHAIN_CONTACT}>
- **Docs**     : <{chain["docs_url"]}>
- **dApp**     : <{chain["dapp_url"]}>
- **Explorer** : <{chain["explorer_url"]}>
- **RPC**      : <{chain["rpc_url"]}>

We're happy to spin up an archive node, ship a chain-spec PR, or pair on
decoder onboarding.
"""


# ---------------------------------------------------------------------------
# Build + write
# ---------------------------------------------------------------------------


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def build_package(
    address_book_path: Path,
    no_timestamp: bool = False,
) -> dict[str, str]:
    """Return a mapping of relative-path-to-content for every file the
    package should contain. Caller decides whether to write or diff."""
    book = _load_address_book(address_book_path)
    manifest = _build_manifest(book, no_timestamp=no_timestamp)

    files: dict[str, str] = {}
    files["INDEXING_MANIFEST.json"] = (
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    for q in QUERY_CATALOGUE:
        files[f"queries/{q['filename']}"] = _build_query(q, book["fee_routes"])
    files["README.md"] = _render_readme(book, manifest)
    files[".generated-from"] = (
        f"sha256  analytics/address-book.json  {_sha256_file(address_book_path)}\n"
    )
    return files


def _normalised_for_diff(payload: str) -> str:
    return re.sub(
        r'"generated_at": "[^"]+"',
        f'"generated_at": "{TIMESTAMP_SENTINEL}"',
        payload,
    )


def _write_files(output_dir: Path, files: dict[str, str]) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "queries").mkdir(parents=True, exist_ok=True)

    # Determine the set of files we *should* have so we can prune any
    # stale leftovers from previous catalogue versions.
    wanted = set(files.keys())
    for existing in output_dir.glob("**/*"):
        if existing.is_dir():
            continue
        rel = existing.relative_to(output_dir).as_posix()
        if rel.startswith("__pycache__") or rel.startswith(".pytest_cache"):
            continue
        if rel not in wanted:
            print(f"  - removing stale {rel}", file=sys.stderr)
            existing.unlink()

    bytes_written = 0
    for rel, payload in files.items():
        target = output_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(payload)
        bytes_written += len(payload.encode())
    print(f"wrote {len(files)} files ({bytes_written} bytes) under {output_dir}")
    return 0


def _check_files(output_dir: Path, files: dict[str, str]) -> int:
    if not output_dir.exists():
        print(
            f"ERROR: --check requires {output_dir} to exist (commit it first).",
            file=sys.stderr,
        )
        return 2
    mismatches: list[str] = []
    for rel, fresh_payload in files.items():
        committed_path = output_dir / rel
        if not committed_path.exists():
            mismatches.append(f"missing file: {rel}")
            continue
        committed = committed_path.read_text()
        if _normalised_for_diff(fresh_payload) == _normalised_for_diff(committed):
            continue
        diff = "".join(
            difflib.unified_diff(
                _normalised_for_diff(committed).splitlines(keepends=True),
                _normalised_for_diff(fresh_payload).splitlines(keepends=True),
                fromfile=f"{rel} (committed)",
                tofile=f"{rel} (regenerated)",
                n=3,
            )
        )
        mismatches.append(f"{rel} drift:\n{diff}")
    # Also flag extra files on disk that the catalogue no longer emits.
    wanted = set(files.keys())
    for existing in output_dir.glob("**/*"):
        if existing.is_dir():
            continue
        rel = existing.relative_to(output_dir).as_posix()
        if rel.startswith("__pycache__") or rel.startswith(".pytest_cache"):
            continue
        if rel not in wanted:
            mismatches.append(f"stale on-disk file not produced by generator: {rel}")
    if mismatches:
        for m in mismatches:
            print("ERROR: " + m, file=sys.stderr)
        print(
            f"FAIL: {len(mismatches)} file(s) out of sync with "
            f"analytics/address-book.json. Run the generator to regenerate.",
            file=sys.stderr,
        )
        return 1
    print(f"OK: {len(files)} file(s) match a fresh regeneration. No drift.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        required=True,
        help="Path to the dune-package directory to write (or check).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate in memory and diff against the committed files. "
        "Exit non-zero on mismatch. Does not write.",
    )
    parser.add_argument(
        "--no-timestamp",
        action="store_true",
        help="Use a stable sentinel for generated_at; recommended for tests.",
    )
    parser.add_argument(
        "--address-book",
        default=str(ADDRESS_BOOK_PATH),
        help=(
            "Override the path to analytics/address-book.json (default: "
            f"{ADDRESS_BOOK_PATH.relative_to(REPO_ROOT)})."
        ),
    )
    args = parser.parse_args(argv)

    output_dir = Path(args.output)
    address_book = Path(args.address_book)

    files = build_package(address_book, no_timestamp=args.no_timestamp)
    if args.check:
        return _check_files(output_dir, files)
    return _write_files(output_dir, files)


if __name__ == "__main__":
    raise SystemExit(main())
