var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/activity/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_0m_q3bn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~ed5.v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_0gybpgt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_07ho8ku._.js")
R.c("server/chunks/ssr/node_modules_next_dist_server_route-modules_app-page_0f6k0sl._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/_0e7r8jy._.js")
R.c("server/chunks/ssr/frontend_src_app_error_tsx_0kciie_._.js")
R.c("server/chunks/ssr/node_modules_073cedv._.js")
R.c("server/chunks/ssr/frontend_src_1285vzr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/frontend_src_app_activity_layout_tsx_13xdr5x._.js")
R.c("server/chunks/ssr/frontend_src_app_activity_error_tsx_0-0stra._.js")
R.c("server/chunks/ssr/frontend_src_0j2piub._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_activity_page_actions_0wvfix~.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/activity/page { MODULE_0 => \"[project]/frontend/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/frontend/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/frontend/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/frontend/src/app/activity/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/frontend/src/app/activity/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/frontend/src/app/activity/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/frontend/src/app/activity/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/activity/page { MODULE_0 => \"[project]/frontend/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/frontend/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/frontend/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/frontend/src/app/activity/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/frontend/src/app/activity/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_8 => \"[project]/frontend/src/app/activity/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_9 => \"[project]/frontend/src/app/activity/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
