import * as fs from 'fs';
import * as fsp from 'fs/promises';
import * as path from 'path';
import { ReconciliationSnapshot } from './types';
import { CapSnapshot } from './cap-enforcer';
import { BreakerState } from './circuit-breakers';
import { HedgeReceipt } from './receipt-store';

const DEFAULT_PROOF_DIR =
  '.autobuilder/initiatives/0007e-hedging-demo/proofs';

export interface ProofWriterInput {
  snapshot: ReconciliationSnapshot;
  capSnapshot: CapSnapshot | null;
  breakerState: BreakerState;
  killSwitchEngaged: boolean;
  mode: 'sandbox' | 'real' | 'demo' | 'unknown';
  dryRun: boolean;
  receipts: HedgeReceipt[];
  /** ISO timestamp string — injectable for deterministic golden-file tests. */
  isoTimestamp?: string;
}

export interface ProofPointer {
  path: string;
  timestamp: number;
  summary: string;
}

/**
 * Render the proof markdown.
 *
 * Determinism: caller supplies `isoTimestamp` so test fixtures snapshot
 * the same text every run. Default behaviour falls back to `new Date()`.
 *
 * Safety: the output is built from typed fields only — there is no
 * `JSON.stringify(env)` or credential pass-through. Tests assert this
 * with a "no secrets" regex sweep.
 */
export function formatProofMarkdown(input: ProofWriterInput): string {
  const iso = input.isoTimestamp ?? new Date(input.snapshot.timestamp).toISOString();
  const breaker = input.breakerState;
  const cap = input.capSnapshot;
  const receipts = input.receipts;
  const exposureRows = input.snapshot.exposures.map((e) => {
    const residual = input.snapshot.residuals.get(e.symbol) ?? 0;
    return `| ${e.symbol} | ${formatNum(e.netDelta)} | ${formatNum(residual)} | ${formatNum(e.absExposure)} |`;
  });
  const receiptRows = receipts.map((r) => {
    const orderId = r.etoroOrderId ?? '—';
    return `| ${shortId(r.id)} | ${r.symbol} | ${r.side} | ${formatNum(r.notionalUsd)} | ${r.success ? 'ok' : (r.error ?? 'failed')} | ${orderId} |`;
  });

  const lines: string[] = [
    `# Demo hedge run — ${iso}`,
    '',
    `**Mode:** \`${input.mode}\`  |  **Dry run:** ${input.dryRun ? 'yes' : 'no'}  |  **Tick:** ${iso}`,
    '',
    '## Breakers & kill switch',
    '',
    `- Breaker: ${breaker.tripped ? `**TRIPPED — ${breaker.reason}**` : 'ok'}${breaker.detail ? ` (${breaker.detail})` : ''}`,
    `- Kill switch: ${input.killSwitchEngaged ? '**ENGAGED**' : 'inactive'}`,
    '',
    '## Caps',
    '',
    cap
      ? `- Day key: \`${cap.dayKey}\`\n- Daily notional: $${formatNum(cap.dailyNotionalUsd)}\n- Daily orders: ${cap.dailyOrders}\n- Cycle orders: ${cap.cycleOrders}`
      : '- (no cap enforcer configured)',
    '',
    '## Receipts',
    '',
  ];

  if (receiptRows.length === 0) {
    lines.push('_No receipts this cycle._');
  } else {
    lines.push('| id | symbol | side | notional (USD) | status | etoroOrderId |');
    lines.push('| --- | --- | --- | ---: | --- | --- |');
    lines.push(...receiptRows);
  }

  lines.push('', '## Exposure before/after', '');
  if (exposureRows.length === 0) {
    lines.push('_No exposures read this cycle._');
  } else {
    lines.push('| symbol | netDelta | residual | absExposure |');
    lines.push('| --- | ---: | ---: | ---: |');
    lines.push(...exposureRows);
  }

  lines.push('', '<!-- generated by backend/hedge-engine/src/proof-writer.ts -->', '');
  return lines.join('\n');
}

function formatNum(n: number): string {
  if (!isFinite(n)) return '—';
  const abs = Math.abs(n);
  const rounded = abs >= 1 ? Math.round(n * 100) / 100 : Math.round(n * 10000) / 10000;
  return String(rounded);
}

function shortId(id: string): string {
  return id.length > 12 ? `${id.slice(0, 6)}…${id.slice(-4)}` : id;
}

function sanitizeFilename(iso: string): string {
  return iso.replace(/[:]/g, '-');
}

export class ProofWriter {
  private readonly dir: string;

  constructor(dir?: string) {
    this.dir = dir ?? process.env.HEDGE_PROOF_DIR ?? DEFAULT_PROOF_DIR;
  }

  getDir(): string {
    return this.dir;
  }

  async writeProof(input: ProofWriterInput): Promise<ProofPointer> {
    await fsp.mkdir(this.dir, { recursive: true });
    const iso = input.isoTimestamp ?? new Date(input.snapshot.timestamp).toISOString();
    const filename = `run-${sanitizeFilename(iso)}.md`;
    const fullPath = path.join(this.dir, filename);
    const markdown = formatProofMarkdown(input);
    await fsp.writeFile(fullPath, markdown, 'utf8');

    const summary = buildSummary(input);
    const pointer: ProofPointer = {
      path: fullPath,
      timestamp: input.snapshot.timestamp,
      summary,
    };
    await this.writeLatestAtomic(pointer);
    return pointer;
  }

  private async writeLatestAtomic(pointer: ProofPointer): Promise<void> {
    const target = path.join(this.dir, 'latest.json');
    const tmp = `${target}.tmp`;
    await fsp.writeFile(tmp, JSON.stringify(pointer, null, 2), 'utf8');
    await fsp.rename(tmp, target);
  }

  /** Read the pointer if present (used by the /hedge/proof/latest route). */
  readLatestPointer(): ProofPointer | null {
    const target = path.join(this.dir, 'latest.json');
    if (!fs.existsSync(target)) return null;
    try {
      return JSON.parse(fs.readFileSync(target, 'utf8')) as ProofPointer;
    } catch {
      return null;
    }
  }
}

function buildSummary(input: ProofWriterInput): string {
  const total = input.receipts.length;
  const ok = input.receipts.filter((r) => r.success).length;
  const failed = total - ok;
  return `${input.mode} ${input.dryRun ? '[dry-run]' : ''} — ${total} receipts (${ok} ok, ${failed} failed)`.trim();
}
